### PR TITLE
Add support for bitwise AND, OR, and XOR

### PR DESCRIPTION
**Pull request by jbernard**
Let me know what you think.  I decided to exclude bitwise NOT since it's compliment applied to decimal values, and I don't have use for it.

Cheers

### CODE REVIEW

**Comment by gregsexton** [comment]
Hi!

Thank you very much for submitting this. I need to quickly verify this and then update the docs and I will merge it in. I don't have a lot of time right now but will get to it soon. 

Thanks,

Greg

**Comment by jbernard** [comment]
- Greg Sexton notifications@github.com wrote:
  > Hi!
  > 
  > Thank you very much for submitting this. I need to quickly verify this and
  > then update the docs and I will merge it in. I don't have a lot of time right
  > now but will get to it soon. 

No worries, I will update the docs to make it a bit easier to manage. I should
have done that with the original pull request anyway :)

Cheers

## 

Jon

**Comment by jbernard** [comment]
Collectively, these commits should cover it.  Let me know if you see any flaws.

**Comment by gregsexton** [comment]
Thank you very much for your work on this.

**Comment by jbernard** [comment]
- Greg Sexton notifications@github.com wrote:
  > Thank you very much for your work on this.

No problem, thanks for merging.  If any issues appear related to these changes
feel free to forward them over, I take full responsibility for my mess ;)

Cheers

## 

Jon

**Pull request merged**
